### ISSUE TITLE
what does "ocLazyLoadStateFactory" used for?

### ISSUE THREAD

**Issue by yssource** [charandas/ui-router-lazy-example#2]
Hi, thanks so much with your example.
I got difficulty to understand the function <a title="ocLazyLoadStateFactory" class="issue-link" href="https://github.com/charandas/ui-router-lazy-example/blob/master/app/js/app.js#L46-L54">
ocLazyLoadStateFactory</a>
It seems that it does never run into the function when I try to debug your example.
I wander what does it used for? 
And more,  Would I change the first parameter to be any other one,  for instance "ocLazyLoad2" at this line? <a title="ocLazyLoadStateFactory" class="issue-link" href="https://github.com/charandas/ui-router-lazy-example/blob/master/app/js/app.js#L56">
$futureStateProvider.stateFactory('ocLazyLoad', ocLazyLoadStateFactory);</a>

Best regards.

**Comment by yssource** [comment]
Now, I got the meanings of this factory. And it works very well with your example. Still thanks so much.

**Comment by charandas** [comment]
Cool. @yssource . Sorry, I took this long to get back. Happy it worked out.
